---
Name: shopmenuconfig
After: framework/routes#coreroutes
---
Product_OrderItem:
  extensions:
    - MenuOrderItemExtension
  required_fields:
    - MenuProductSelection
Product:
  extensions:
    - MenuProductExtension

Order:
  extensions:
    - MenuOrderExtension